# importMatched and importUnmatched: structure and dimensions

test_that("importMatched returns correct structure for precomp_testdata", {
    filename <- system.file("extdata", "precomp_testdata.dat", package = "maxscoreest")
    skip_if_not(nzchar(filename))
    x <- importMatched(filename)
    expect_type(x, "list")
    expect_true("noM" %in% names(x))
    expect_true("noU" %in% names(x))
    expect_true("noD" %in% names(x))
    expect_true("noAttr" %in% names(x))
    expect_true("distanceMatrices" %in% names(x))
    expect_true("matchMatrices" %in% names(x))
    expect_true("mate" %in% names(x))
    expect_equal(length(x$distanceMatrices), x$noM)
    expect_equal(length(x$matchMatrices), x$noM)
    expect_equal(length(x$mate), x$noM)
    expect_equal(length(x$noU), x$noM)
    expect_equal(length(x$noD), x$noM)
    expect_true(x$noM >= 1L)
    expect_true(x$noAttr >= 1L)
    for (m in seq_len(x$noM)) {
        expect_equal(dim(x$distanceMatrices[[m]]), c(x$noAttr, x$noD[m], x$noU[m]))
        expect_equal(dim(x$matchMatrices[[m]]), c(x$noD[m], x$noU[m]))
    }
})

test_that("importUnmatched returns correct structure for extdata files", {
    filenameUp <- system.file("extdata", "unmatched_testdata_up.csv", package = "maxscoreest")
    filenameDn <- system.file("extdata", "unmatched_testdata_dn.csv", package = "maxscoreest")
    skip_if_not(nzchar(filenameUp) && nzchar(filenameDn))
    x <- importUnmatched(filenameUp, filenameDn)
    expect_type(x, "list")
    expect_true("noM" %in% names(x))
    expect_true("noU" %in% names(x))
    expect_true("noD" %in% names(x))
    expect_true("noAttr" %in% names(x))
    expect_true("attributeMatricesUp" %in% names(x))
    expect_true("attributeMatricesDn" %in% names(x))
    expect_true("quotasUp" %in% names(x))
    expect_true("quotasDn" %in% names(x))
    expect_equal(length(x$attributeMatricesUp), x$noM)
    expect_equal(length(x$attributeMatricesDn), x$noM)
    expect_equal(length(x$quotasUp), x$noM)
    expect_equal(length(x$quotasDn), x$noM)
    expect_equal(length(x$noU), x$noM)
    expect_equal(length(x$noD), x$noM)
    expect_true(x$noM >= 1L)
    expect_true(x$noAttr >= 1L)
    for (m in seq_len(x$noM)) {
        expect_equal(nrow(x$attributeMatricesUp[[m]]), x$noAttr)
        expect_equal(ncol(x$attributeMatricesUp[[m]]), x$noU[m])
        expect_equal(nrow(x$attributeMatricesDn[[m]]), x$noAttr)
        expect_equal(ncol(x$attributeMatricesDn[[m]]), x$noD[m])
        expect_equal(length(x$quotasUp[[m]]), x$noU[m])
        expect_equal(length(x$quotasDn[[m]]), x$noD[m])
    }
})
